<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AokuvueDevInstaller</AssemblyName>
    <RootNamespace>AokuvueDevInstaller</RootNamespace>
    <Version>0.2.0</Version>
    <ApplicationIcon>..\..\src\main\resources\images\aokuvue.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
